# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[manager]
cwd = { fg = "#94e2d5" }

# Hovered
hovered = { reversed = true }
preview_hovered = { underline = true }

# Find
find_keyword = { fg = "#f9e2af", bold = true, italic = true, underline = true }
find_position = { fg = "#f5c2e7", bg = "reset", bold = true, italic = true }

# Marker
marker_copied = { fg = "#a6e3a1", bg = "#a6e3a1" }
marker_cut = { fg = "#f38ba8", bg = "#f38ba8" }
marker_marked = { fg = "#94e2d5", bg = "#94e2d5" }
marker_selected = { fg = "#f9e2af", bg = "#f9e2af" }

# Tab
tab_active = { reversed = true }
tab_inactive = {}
tab_width = 1

# Count
count_copied = { fg = "#1e1e2e", bg = "#a6e3a1" }
count_cut = { fg = "#1e1e2e", bg = "#f38ba8" }
count_selected = { fg = "#1e1e2e", bg = "#f9e2af" }

# Border
border_symbol = "│"
border_style = { fg = "#7f849c" }

# : }}}


# : Status {{{

[status]
separator_open = ""
separator_close = ""
separator_style = { fg = "#45475a", bg = "#45475a" }

# Mode
mode_normal = { fg = "#1e1e2e", bg = "#89b4fa", bold = true }
mode_select = { fg = "#1e1e2e", bg = "#a6e3a1", bold = true }
mode_unset = { fg = "#1e1e2e", bg = "#f2cdcd", bold = true }

# Progress
progress_label = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#89b4fa", bg = "#45475a" }
progress_error = { fg = "#f38ba8", bg = "#45475a" }

# Permissions
permissions_t = { fg = "#89b4fa" }
permissions_r = { fg = "#f9e2af" }
permissions_w = { fg = "#f38ba8" }
permissions_x = { fg = "#a6e3a1" }
permissions_s = { fg = "#7f849c" }

# : }}}


# : Select {{{

[select]
border = { fg = "#89b4fa" }
active = { fg = "#f5c2e7", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border = { fg = "#89b4fa" }
title = {}
value = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[completion]
border = { fg = "#89b4fa" }

# : }}}


# : Tasks {{{

[tasks]
border = { fg = "#89b4fa" }
title = {}
hovered = { fg = "#f5c2e7", underline = true }

# : }}}


# : Which {{{

[which]
mask = { bg = "#313244" }
cand = { fg = "#94e2d5" }
rest = { fg = "#9399b2" }
desc = { fg = "#f5c2e7" }
separator = "  "
separator_style = { fg = "#585b70" }

# : }}}


# : Help {{{

[help]
on = { fg = "#94e2d5" }
run = { fg = "#f5c2e7" }
hovered = { reversed = true, bold = true }
footer = { fg = "#45475a", bg = "#cdd6f4" }

# : }}}


# : Notify {{{

[notify]
title_info = { fg = "#a6e3a1" }
title_warn = { fg = "#f9e2af" }
title_error = { fg = "#f38ba8" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
  # Images
  { mime = "image/*", fg = "#94e2d5" },

  # Media
  { mime = "{audio,video}/*", fg = "#f9e2af" },

  # Archives
  { mime = "application/*zip", fg = "#f5c2e7" },
  { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#f5c2e7" },

  # Documents
  { mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#a6e3a1" },

  # Fallback
  { name = "*", fg = "#cdd6f4" },
  { name = "*/", fg = "#89b4fa" },
]

[icon]

rules = [
  # Programming
  { name = "*.cpp", text = "", fg = "#519aba" },
  { name = "*.css", text = "", fg = "#42a5f5" },
  { name = "*.c", text = "", fg = "#599eff" },
  { name = "*.fish", text = "" },
  { name = "*.go", text = "", fg = "#519aba" },
  { name = "*.hpp", text = "", fg = "#a074c4" },
  { name = "*.h", text = "", fg = "#a074c4" },
  { name = "*.htm", text = "", fg = "#e44d26" },
  { name = "*.html", text = "", fg = "#e44d26" },
  { name = "*.java", text = "", fg = "#cc3e44" },
  { name = "*.js", text = "", fg = "#F1F134" },
  { name = "*.jsx", text = "", fg = "#20c2e3" },
  { name = "*.lua", text = "", fg = "#51a0cf" },
  { name = "*.nix", text = "", fg = "#7ab1db" },
  { name = "*.php", text = "" },
  { name = "*.rb", text = "" },
  { name = "*.rs", text = "", fg = "#dea584" },
  { name = "*.scss", text = "" },
  { name = "*.sh", text = "", fg = "#4d5a5e" },
  { name = "*.swift", text = "" },
  { name = "*.ts", text = "", fg = "#519aba" },
  { name = "*.tsx", text = "" },
  { name = "*.vim", text = "" },
  { name = "*.vue", text = "󰡄" },
  { name = "*.py", text = "", fg = "#ffbc03" },
  { name = "*.pyc", text = "", fg = "#ffe291" },

  # Text
  { name = "*.txt", text = "", fg = "#bbbbbb" },
  { name = "*.csv", text = "", fg = "#89e051" },
  { name = "*.json", text = "", fg = "#cbcb41" },
  { name = "*.conf", text = "", fg = "#6d8086" },     # Configuration
  { name = "*.ini", text = "", fg = "#6d8086" },
  { name = "*.yaml", text = "", fg = "#6d8086" },
  { name = "*.yml", text = "", fg = "#6d8086" },
  { name = "*.toml", text = "", fg = "#6d8086" },
  { name = "*.org", text = "", fg = "#77aa99" },
  { name = "*.tex", text = "󰙩", fg = "#3d6117" },      # Plaintext typesetting
  { name = "*.typ", text = "󰙩", fg = "#0e606a" },
  { name = "*.markdown", text = "", fg = "#519aba" }, # Markdown
  { name = "*.md", text = "", fg = "#519aba" },
  { name = "*.mdx", text = "", fg = "#519aba" },
  { name = "*.rmd", text = "", fg = "#519aba" },

  # Archives
  { name = "*.7z", text = "" },
  { name = "*.ace", text = "" },
  { name = "*.alz", text = "" },
  { name = "*.arc", text = "" },
  { name = "*.arj", text = "" },
  { name = "*.bz2", text = "" },
  { name = "*.bz", text = "" },
  { name = "*.cab", text = "" },
  { name = "*.cpio", text = "" },
  { name = "*.deb", text = "" },
  { name = "*.dwm", text = "" },
  { name = "*.dz", text = "" },
  { name = "*.ear", text = "" },
  { name = "*.esd", text = "" },
  { name = "*.gz", text = "" },
  { name = "*.jar", text = "" },
  { name = "*.lha", text = "" },
  { name = "*.lrz", text = "" },
  { name = "*.lz4", text = "" },
  { name = "*.lzh", text = "" },
  { name = "*.lzma", text = "" },
  { name = "*.lzo", text = "" },
  { name = "*.lz", text = "" },
  { name = "*.rar", text = "" },
  { name = "*.rpm", text = "" },
  { name = "*.rz", text = "" },
  { name = "*.sar", text = "" },
  { name = "*.swm", text = "" },
  { name = "*.t7z", text = "" },
  { name = "*.tar", text = "" },
  { name = "*.taz", text = "" },
  { name = "*.tbz2", text = "" },
  { name = "*.tbz", text = "" },
  { name = "*.tgz", text = "" },
  { name = "*.tlz", text = "" },
  { name = "*.txz", text = "" },
  { name = "*.tzo", text = "" },
  { name = "*.tzst", text = "" },
  { name = "*.tz", text = "" },
  { name = "*.war", text = "" },
  { name = "*.wim", text = "" },
  { name = "*.xz", text = "" },
  { name = "*.zip", text = "" },
  { name = "*.zoo", text = "" },
  { name = "*.zst", text = "" },
  { name = "*.z", text = "" },

  # Images
  { name = "*.bmp", text = "" },   # Lossless
  { name = "*.gif", text = "" },
  { name = "*.png", text = "" },
  { name = "*.tiff", text = "" },
  { name = "*.webp", text = "" },
  { name = "*.jpeg", text = "" },  # Lossy
  { name = "*.jpg", text = "" },
  { name = "*.mjpeg", text = "" },
  { name = "*.mjpg", text = "" },
  { name = "*.mng", text = "" },
  { name = "*.pbm", text = "" },
  { name = "*.pcx", text = "" },
  { name = "*.pgm", text = "" },
  { name = "*.ppm", text = "" },
  { name = "*.svg", text = "" },
  { name = "*.svgz", text = "" },
  { name = "*.tga", text = "" },
  { name = "*.tif", text = "" },
  { name = "*.xbm", text = "" },
  { name = "*.xpm", text = "" },

  # Movies
  { name = "*.asf", text = "" },
  { name = "*.avi", text = "" },
  { name = "*.cgm", text = "" },
  { name = "*.dl", text = "" },
  { name = "*.emf", text = "" },
  { name = "*.flc", text = "" },
  { name = "*.fli", text = "" },
  { name = "*.flv", text = "" },
  { name = "*.gl", text = "" },
  { name = "*.m2v", text = "" },
  { name = "*.m4v", text = "" },
  { name = "*.mkv", text = "" },
  { name = "*.mov", text = "" },
  { name = "*.mp4", text = "" },
  { name = "*.mp4v", text = "" },
  { name = "*.mpeg", text = "" },
  { name = "*.mpg", text = "" },
  { name = "*.nuv", text = "" },
  { name = "*.ogm", text = "" },
  { name = "*.ogv", text = "" },
  { name = "*.ogx", text = "" },
  { name = "*.qt", text = "" },
  { name = "*.rm", text = "" },
  { name = "*.rmvb", text = "" },
  { name = "*.vob", text = "" },
  { name = "*.webm", text = "" },
  { name = "*.wmv", text = "" },
  { name = "*.xcf", text = "" },
  { name = "*.xwd", text = "" },
  { name = "*.yuv", text = "" },

  # Audio
  { name = "*.aac", text = "" },
  { name = "*.au", text = "" },
  { name = "*.flac", text = "" },
  { name = "*.m4a", text = "" },
  { name = "*.mid", text = "" },
  { name = "*.midi", text = "" },
  { name = "*.mka", text = "" },
  { name = "*.mp3", text = "" },
  { name = "*.mpc", text = "" },
  { name = "*.oga", text = "" },
  { name = "*.ogg", text = "" },
  { name = "*.opus", text = "" },
  { name = "*.ra", text = "" },
  { name = "*.spx", text = "" },
  { name = "*.wav", text = "" },
  { name = "*.xspf", text = "" },

  # Documents
  { name = "*.pdf", text = "", fg = "#b30b00" },  # Printable
  { name = "*.doc", text = "", fg = "#185abd" },  # Non plaintext docs
  { name = "*.doct", text = "", fg = "#185abd" },
  { name = "*.docx", text = "", fg = "#185abd" },
  { name = "*.dot", text = "", fg = "#185abd" },
  { name = "*.pom", text = "󰈩", fg = "#cb4a32" },  # Presentations
  { name = "*.pot", text = "󰈩", fg = "#cb4a32" },
  { name = "*.potx", text = "󰈩", fg = "#cb4a32" },
  { name = "*.ppm", text = "󰈩", fg = "#cb4a32" },
  { name = "*.ppmx", text = "󰈩", fg = "#cb4a32" },
  { name = "*.pps", text = "󰈩", fg = "#cb4a32" },
  { name = "*.ppsx", text = "󰈩", fg = "#cb4a32" },
  { name = "*.ppt", text = "󰈩", fg = "#cb4a32" },
  { name = "*.pptx", text = "󰈩", fg = "#cb4a32" },
  { name = "*.xlc", text = "" },
  { name = "*.xlm", text = "" },
  { name = "*.xls", text = "" },
  { name = "*.xlsm", text = "" },
  { name = "*.xlsx", text = "" },
  { name = "*.xlt", text = "" },
  { name = "*.ods", text = "" },
  { name = "*.ots", text = "" },
  { name = "*.odg", text = "󰽉" },

  # Lockfiles
  { name = "*.lock", text = "", fg = "#bbbbbb" },

  # Misc
  { name = "*.bin", text = "" },
  { name = "*.exe", text = "" },
  { name = "*.pkg", text = "" },

  # Dotfiles
  { name = ".DS_Store", text = "" },
  { name = ".bashprofile", text = "" },
  { name = ".bashrc", text = "" },
  { name = ".gitattributes", text = "" },
  { name = ".gitignore", text = "" },
  { name = ".gitmodules", text = "" },
  { name = ".vimrc", text = "" },
  { name = ".zprofile", text = "" },
  { name = ".zshenv", text = "" },
  { name = ".zshrc", text = "" },

  # Named files
  { name = "COPYING", text = "󰿃" },
  { name = "Containerfile", text = "󰡨", fg = "#458ee6" },
  { name = "Dockerfile", text = "󰡨", fg = "#458ee6" },
  { name = "LICENSE", text = "", fg = "#d0bf41" },

  # Default
  { name = "*", text = "", is = "exec" },
  { name = "*", text = "" },
  { name = "*/", text = "󰝰", fg = "yellow" },
]

# : }}}
