[font]
size = 11
normal = { family = "CaskaydiaCove Nerd Font", style = "Medium" }
bold = { family = "CaskaydiaCove Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaCove Nerd Font", style = "Italic" }

[window]
opacity = 0.85

[colors.primary]
background = "#000000"
